# Generated by Django 2.2 on 2020-08-29 06:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListLanguagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
                ('code', models.CharField(max_length=10, verbose_name='Код языка (ISO 639-1)')),
            ],
            options={
                'db_table': 'list_languages',
            },
        ),
        migrations.CreateModel(
            name='TranslatedTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', ckeditor.fields.RichTextField(verbose_name='Текст для перевода')),
                ('output_text', ckeditor.fields.RichTextField(verbose_name='Переведенный текст')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_translator.ListLanguagesModel')),
            ],
            options={
                'db_table': 'translated_text',
            },
        ),
    ]
