# Generated by Django 2.2 on 2020-08-29 11:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtextmodel',
            name='output_text',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Переведенный текст'),
        ),
        migrations.AlterUniqueTogether(
            name='listlanguagesmodel',
            unique_together={('name', 'code')},
        ),
    ]
