# Generated by Django 2.2 on 2020-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_translator', '0002_auto_20200829_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listlanguagesmodel',
            options={'verbose_name': 'Досутпные языки для первода'},
        ),
        migrations.AlterModelOptions(
            name='translatedtextmodel',
            options={'verbose_name': 'Текст до перевода и после'},
        ),
        migrations.AlterField(
            model_name='listlanguagesmodel',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код языка (ISO 639-1)'),
        ),
        migrations.AlterField(
            model_name='listlanguagesmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название языка'),
        ),
        migrations.AlterUniqueTogether(
            name='listlanguagesmodel',
            unique_together=set(),
        ),
    ]
